### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by thiagolages** [thiagolages/chess-game-cpp#1]
# Chess To-Do List

## Mandatory to make the game playable
- [x] Render background (board)
- [x] Create ChessPiece class
- [x] Create Game class
- [x] Create all pieces classes, derived from ChessPiece 
- [x] Render all pawns
- [x] Render all minor pieces
- [x] Render all kings and queens
- [x] Render moving a piece
- [x] Render capturing a piece
- [x] Handle player turns
- [x] Calculate all possible moves on all Pieces
- [x] Calculate legal moves
- [x] Show all possible moves on the board
- [x] Handle pawn moving and capturing in different squares
- [ ] Identify if king would put himself in check
- [ ] Identify check
- [ ] Identify check mate

## Important but not urgent
- [x] Show possible moves on the screen
- [ ] Castles
- [ ] En passant
- [ ] Pawn promotion
- [ ] Square highlight with right-click
- [ ] Draw arrows with right-click

## Less important or special cases
- [ ] Create system to navigate through moves using arrow keys (go back one move, for ex.)
- [ ] Stalemate
- [ ] Draw by repetition
- [ ] Draw by 50-move rule

More items can be added/removed/modified if needed to.
